Rodando `eslint --fix` em todo projeto.
lukinhasl157/thepunisher pull request #9
Opened 2020-05-27 23:32 UTC by Tsugami

- rodando eslint fix em todo aplicação.
- arrumando os nomes dos comandos que estão com PATH do comando.
- removendo node-opus e instalando o @discord.js/opus.
- movendo o eslint de depedends para devDepedends no package.json.

2020-05-27 23:36 UTC, almeidx requested changes
remove package-lock.json

2020-05-27 23:38 UTC, Tsugami commented
ta maluco?

2020-05-27 23:55 UTC, almeidx approved these changes

2020-05-28 02:33 UTC, lukinhasl157 commented
nao

2020-06-07 11:42 UTC, merged

2020-06-07 11:43 UTC, almeidx commented
dei merge pq eu posso :ez: